name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      # when Github updates their Ubuntu image on Nov29 2021 we can switch to it
      # as we don't need to manually add 16
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build-ci
      - run: npm run test-ci